
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=sanjana
      - POSTGRES_PASSWORD=sura
    ports:
      - "5432:5432"
   

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
